device: &device cuda:0
rotation_type: &rotation_type euler
rotation_dim: &rotation_dim 3

ncols: 120
epochs: &epochs 100
print_freq: 500
validate_freq: 1
save_root: ./Experiments/qgc
save_top_n: 20
log_dir: logs
seed: 3407
norm_type: &norm_type minmax11
guidence_type: &guidence_type "fine" # fine
frozen_clip: False

data:
  name: refinement
  train:
    data_root: &data_root "./data/oakink"
    pose_path: ./Experiments/idgc/test_results/epoch_1_train/matched_results.json
    sample_in_pose: &sample_in_pose True
    guidence_type: *guidence_type
    rotation_type: *rotation_type
    norm_type: *norm_type 
    batch_size: 32
    num_workers: 8

  val:
    data_root: *data_root
    pose_path: ./Experiments/idgc/test_results/epoch_1_test/matched_results.json
    sample_in_pose: True
    guidence_type: *guidence_type
    rotation_type: *rotation_type
    norm_type: *norm_type 
    batch_size: 32
    num_workers: 8

model:
  name: IRF
  steps: 100
  schedule_cfg:
    beta: [0.0001, 0.01]
    beta_schedule: 'linear'
    s: 0.008
  rand_t_type: 'half' # 'half' or 'all'
  loss_type: 'l2' # 'l1' or 'l2'
  out_sigmoid: False
  pred_abs: False
  device: *device
  rotation_type: *rotation_type

  decoder:
    name: unet
    task_num: 0
    cls_dim: 0
    use_guidence: False
    use_obj: True
    use_hand: True
    plus_condition_type: ()
    trans_condition_type: "obj_hand"
    backbone:
      name: pointnet2
      use_pooling: False
      layer1:
        npoint: 1024
        radius_list: [0.02]
        nsample_list: [64]
        mlp_list: [0, 64, 128]
      layer2:
        npoint: 128
        radius_list: [0.04]
        nsample_list: [16]
        mlp_list: [128, 256, 256]
      layer3:
        npoint: 16
        radius_list: [0.08]
        nsample_list: [4]
        mlp_list:
          - 256
          - 512
          - &encoder_out 512
      use_xyz: true
      normalize_xyz: true

    hand_backbone:
      name: pointnet2
      use_pooling: False
      layer1:
        npoint: 1024
        radius_list: [0.02]
        nsample_list: [64]
        mlp_list: [0, 64, 128]
      layer2:
        npoint: 128
        radius_list: [0.04]
        nsample_list: [16]
        mlp_list: [128, 256, 256]
      layer3:
        npoint: 16
        radius_list: [0.08]
        nsample_list: [4]
        mlp_list:
          - 256
          - 512
          - *encoder_out
      use_xyz: true
      normalize_xyz: true

    d_x: 28 # placeholder
    d_model: 512
    time_embed_mult: 2
    nblocks: 4
    resblock_dropout: 0.0
    transformer_num_heads: 8
    transformer_dim_head: 64
    transformer_dropout: 0.1
    transformer_depth: 1
    transformer_mult_ff: 2
    context_dim: 512
    use_position_embedding: false # for input x

  criterion:
    hand_model:
      mjcf_path: ./data/mjcf/shadow_hand.xml
      mesh_path: ./data/mjcf/meshes
      n_surface_points: 1024
      contact_points_path: ./data/mjcf/contact_points.json
      penetration_points_path: ./data/mjcf/penetration_points.json
      fingertip_points_path: ./data/mjcf/fingertip.json
    loss_weights:
      hand_chamfer: 1.0
      para: 10.0
      obj_penetration: 100.0
      self_penetration: 10.0
      cmap: 10.0

    cost_weights:
      hand_mesh: 0.0
      qpos: 1.0
      translation: 2.0
      rotation: 2.0
    device: *device
    rotation_type: *rotation_type
    norm_type: *norm_type


optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 1.0e-4

scheduler:
  name: cosine
  t_max: *epochs
  min_lr: 1.0e-5
